[package]
name = "day-5"
version = "0.1.0"
authors = ["Matthew Diamant <matthewdiamant@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "day-5"
path = "day-5.rs"
